name: Schedule Record

on:
  schedule:
    # 12:01 MMT → 05:31 UTC
    - cron: "31 5 * * *"
    # 16:30 MMT → 10:00 UTC
    - cron: "0 10 * * *"

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytz requests flask

      - name: Run script
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data.json
          git commit -m "Auto update record"
          git push